name: diabetes_detection_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  mobile_scanner: ^3.5.5
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0
  qr: ^3.0.2
  sqflite: ^2.0.0+4
  crypto: ^3.0.2
  pointycastle: ^3.6.2
  uuid: ^3.0.6
  tflite: ^1.1.2
  http: ^0.13.5
  tflite_flutter: ^0.10.4
  pie_chart: ^5.4.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - diabetes_model.tflite